name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3  # Updated to v3

      - name: Setup Python
        uses: actions/setup-python@v4  # Updated to v4
        with:
          python-version: '3.x'

      # Uncomment and modify this step if you need to install dependencies
      #- name: Install dependencies
      #  run: |
      #    python -m pip install --upgrade pip
      #    pip install -r requirements.txt

      - name: Generate Snake animation
        run: |
          python3 generate-snake.py --output dist/snake.svg
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dist/snake.svg
          git commit -m 'Generate new snake animation'
          git push

      - name: Deploy Snake animation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
